import './globals.css';
import styles from './Header.module.css'

export const metadata = {
  title: 'To do',
  description: 'Generated by Next.js. This app is a to do list where you can create and delete tasks',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        {/* Heres the routes */}
        <header className={styles.headerContainer}>
          <nav className={styles.navContainer}>
            <a href="/">Home</a>
            <a href="/todo-list">To do</a>
          </nav>
        </header>
        <main>{children}</main>
      </body>
    </html>
  )
}
